name: v2ray-app
services:
  v2ray:
    public: true
    build: 
      context: .
      dockerfile: Dockerfile
    image: okteto.dev/v2ray-app
    ports:
      - 8080
    resources:
      cpu: 100m
      memory: 128Mi
      storage: 128Mi