# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 输出IP
      - name: IP
        run: curl ifconfig.me  
      
      # 设置服务器时区为东八区 
      - name: Set time zone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it          
      - uses: actions/checkout@v2
      
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.0.3
        
      - name: install v2ray
        run: |
          docker build -t v2ray:latest .
          docker images
          docker run -p8080:8080 v2ray:latest 
                             
      - name: coutinue workflows
        run: sudo touch /tmp/continue
        
      - name: Start SSH via tmate
        uses: P3TERX/ssh2actions@main
